### ISSUE TITLE
Expected BLEU score on test data?

### ISSUE THREAD

**Issue by tnq177** [lmthang/nmt.matlab#10]
Hi,

Just want to ask what the expected BLEU score on the given test data is please? Thanks!

**Comment by lmthang** [comment]
Hi Toan,

If you mean the toy test data, then I don't have the number. But you can compute them! We have provided all models and data used in our papers. See here http://nlp.stanford.edu/projects/nmt/.
-Thang

**Comment by tnq177** [comment]
@lmthang  thanks!
